keys:
  - &camellya_host age1kt66h37ezqaryvef402f0665aavu3mpj2l7trdkqctpjl6zeeveswgc50j

creation_rules:
  - path_regex: hosts/camellya/secrets\.yaml$
    key_groups:
      - age:
          - *camellya_host
